2020-10-17 13:08:40,187 INFO: Microblog startup [in C:\Users\ponei\github\CrowdQuiz\app\__init__.py:48]
2020-10-17 13:08:46,205 INFO: Microblog startup [in C:\Users\ponei\github\CrowdQuiz\app\__init__.py:48]
2020-10-17 13:10:13,642 ERROR: Exception on /reset_password_request [POST] [in c:\users\ponei\github\crowdquiz\venv\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "c:\users\ponei\github\crowdquiz\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\ponei\github\crowdquiz\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\ponei\github\crowdquiz\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\ponei\github\crowdquiz\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\ponei\github\crowdquiz\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\ponei\github\crowdquiz\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\ponei\github\CrowdQuiz\app\routes.py", line 94, in reset_password_request
    send_password_reset_email(user)
  File "C:\Users\ponei\github\CrowdQuiz\app\email.py", line 19, in send_password_reset_email
    sender=app.config['ADMINS'][0],
NameError: name 'app' is not defined
2020-10-17 13:11:04,935 INFO: Microblog startup [in C:\Users\ponei\github\CrowdQuiz\app\__init__.py:48]
